/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public static void main(String args[]) {
    	Library lib = new Library();
    	if(lib.someLibraryMethod()) {
	    	System.out.println("When there is a fire:");
	    	System.out.println("1.\tgit commit");
	    	System.out.println("2.\tgit push");
	    	System.out.println("3.\trun");
    	}
    }
    
    public boolean someLibraryMethod() {
    	return true;
    }
}
